[WIP] Retrain huwiki models
wikimedia/editquality pull request #207
Opened 2019-07-18 01:49 UTC by accraze

WIP

Retraining the damaging/goodfaith models for huwiki

2019-07-18 01:56 UTC, accraze commented
@halfak I'm getting an error when I try to create the new `labeled_revisions` data

```
make datasets/huwiki.labeled_revisions.json
./utility merge_labels datasets/huwiki.badfaith_relabeling_revisions.500_2019.json datasets/huwiki.original_labeled_revisions.40k_2016.json > datasets/huwiki.labeled_revisions.json
Traceback (most recent call last):
  File "./utility", line 4, in <module>
    editquality.main()
  File "/srv/home/accraze/editquality/editquality/editquality.py", line 50, in main
    module.main(sys.argv[2:])
  File "/srv/home/accraze/editquality/editquality/utilities/merge_labels.py", line 73, in main
    jsonlines = [json.dumps(l) for l in merged_labels]
  File "/srv/home/accraze/editquality/editquality/utilities/merge_labels.py", line 106, in run
    if not revision['autolabel']['needs_review']:
KeyError: 'needs_review'
```
The new data looks fine, but when I look at `datasets/huwiki.original_labeled_revisions.40k_2016.json`, I see that each revision looks similar to this:

```
{"goodfaith": true, "auto_labeled": false,  "autolabel": {}, "damaging": false, "rev_id": 16416637,}
```
(note the `"autolabel":{}` )

Am I forgetting a step? Or maybe an incorrect config?

2019-07-18 13:10 UTC, halfak commented
They have an autolabel field when they get downloaded.  You can see that here: https://labels.wmflabs.org/campaigns/huwiki/92/?tasks

Still digging...

2019-07-18 13:15 UTC, halfak commented
When I make the badfaith relabeling dataset (should probably change that name to "badfaith_or_damaging" to avoid confusion), it includes an autolabel field. 

```
{"goodfaith": false, "auto_labeled": false, "reverted_for_damage": false, "autolabel": {"review_reason": null, "needs_review": true}, "damaging": true, "rev_id": 17276091}
```

2019-07-18 15:18 UTC, accraze commented
@halfak yeah the badfaith dataset looks fine, but the `autolabel` field is empty on the original dataset (`datasets/huwiki.original_labeled_revisions.40k_2016.json`). I get the error when I try to merge the two of them together. Should I even be merging the old and new labels together?

2019-07-18 21:56 UTC, halfak commented
OK I think I have figured out what the source of this is.  So very few of the records are missing autolabel.  It looks like it is coming from observations stored in Wikilabels that are not appearing in the autolabel dataset.  This is because the articles the revisions belong to have been deleted.  

Here's an example of such a record: 
```
{"auto_labeled": false, "rev_id": 16318074, "goodfaith": true, "damaging": true, "autolabel": {}}
```

Here's the diff that the revision points to: 
https://hu.wikipedia.org/wiki/?diff=16318074

Here's what I think that we should do:
1. Update the merge_labels utility so that it doesn't error when that field isn't present.  Instead it should just assume the worst (`"needs review": true`).
2. Re-run this model pipeline.  
3. Victory.

2019-07-24 17:22 UTC, halfak requested changes
Just one minor change in data file naming.  Otherwise this looks good.

2019-07-24 17:22 UTC, halfak commented on config/wikis/huwiki.yaml
> +    sample: labeled_revisions.40k_2019
Should still be 2016 as the underlying data is from 2016.

2019-07-24 17:22 UTC, halfak commented on editquality/utilities/merge_labels.py
> +    return revision['autolabel'].get('needs_review', True)
I like it.

2019-07-24 17:22 UTC, halfak commented on editquality/utilities/tests/test_merge_labels.py
> +    assert res == True  # noqa
Nice work including a set of tests.

2019-07-24 21:24 UTC, merged