T166952: add no ha option for huwiki
wikimedia/editquality pull request #70
Opened 2017-06-05 22:05 UTC by Pix1234

2017-06-05 22:21 UTC, Ladsgroup requested changes

2017-06-05 22:21 UTC, Ladsgroup commented on editquality/feature_lists/huwiki.py
> +    informals_no_ha = english.informals.excluding(["ha"])
This will end up as syntax error, please move it outside of definition of the list.

2017-06-05 22:22 UTC, Ladsgroup commented
Also it would be great to reduce number of the commits, I can squash them to one commit when merging too though. As you prefer.

2017-06-06 00:07 UTC, Ladsgroup approved these changes

2017-06-06 00:08 UTC, merged

2017-06-06 00:08 UTC, Ladsgroup commented
I squashed it as ten commits for this doesn't make sense.

2017-06-06 14:32 UTC, halfak commented
:P  wasn't supposed to merge until we have a new model